"""add ai + update directory table

Revision ID: 6296955b45c6
Revises: f33fd9cc72aa
Create Date: 2026-01-04 19:48:19.723906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '6296955b45c6'
down_revision: Union[str, Sequence[str], None] = 'f33fd9cc72aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)

    existing_tables = set(inspector.get_table_names())
    vendor_indexes = {idx["name"] for idx in inspector.get_indexes("vendors")} if "vendors" in existing_tables else set()

    # Drop legacy vendor indexes/table if they exist (SQLite: use IF EXISTS semantics manually)
    if "ix_vendors_id" in vendor_indexes:
        op.execute("DROP INDEX IF EXISTS ix_vendors_id")
    if "ix_vendors_name" in vendor_indexes:
        op.execute("DROP INDEX IF EXISTS ix_vendors_name")
    if "vendors" in existing_tables:
        op.execute("DROP TABLE IF EXISTS vendors")

    # Update vendor_materials FK to point to vendor_profiles
    if "vendor_materials" in existing_tables:
        fks = inspector.get_foreign_keys("vendor_materials")
        refers_vendors = any(fk.get("referred_table") == "vendors" for fk in fks)

        if refers_vendors and "vendors" not in existing_tables:
            # Recreate table with correct FK when legacy vendors table is missing
            op.execute("DROP TABLE IF EXISTS vendor_materials")
            op.create_table(
                "vendor_materials",
                sa.Column("id", sa.Integer(), primary_key=True, index=True),
                sa.Column("vendor_id", sa.Integer(), sa.ForeignKey("vendor_profiles.id", ondelete="CASCADE")),
                sa.Column("material_id", sa.Integer(), sa.ForeignKey("materials.id", ondelete="CASCADE")),
                sa.Column("price", sa.Float(), nullable=True),
            )
        elif refers_vendors:
            with op.batch_alter_table("vendor_materials") as batch_op:
                for fk in fks:
                    if fk.get("referred_table") == "vendors":
                        batch_op.drop_constraint(fk["name"], type_="foreignkey")
                batch_op.create_foreign_key(
                    None,
                    "vendor_profiles",
                    ["vendor_id"],
                    ["id"],
                    ondelete="CASCADE",
                )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor_materials', type_='foreignkey')
    op.create_foreign_key(None, 'vendor_materials', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.create_table('vendors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('category', sa.VARCHAR(length=120), nullable=False),
    sa.Column('location', sa.VARCHAR(length=120), nullable=True),
    sa.Column('supplier_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=False),
    sa.Column('verified', sa.BOOLEAN(), nullable=False),
    sa.Column('short_description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    # ### end Alembic commands ###
