"""add ai tables

Revision ID: 726bdc501903
Revises: 6296955b45c6
Create Date: 2026-01-04 20:00:51.513847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '726bdc501903'
down_revision: Union[str, Sequence[str], None] = '6296955b45c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if "ai_threads" not in existing_tables:
        op.create_table(
            "ai_threads",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column("user_id", sa.String(), nullable=False),
            sa.Column("project_id", sa.String(), nullable=True),
            sa.Column("title", sa.String(length=200), nullable=False),
            sa.Column("is_archived", sa.Boolean(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.Column("updated_at", sa.DateTime(), nullable=False),
            sa.Column("last_message_at", sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_ai_threads_project_id"), "ai_threads", ["project_id"], unique=False)
        op.create_index(op.f("ix_ai_threads_user_id"), "ai_threads", ["user_id"], unique=False)

    if "ai_messages" not in existing_tables:
        op.create_table(
            "ai_messages",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column("thread_id", sa.String(), nullable=False),
            sa.Column("role", sa.String(length=20), nullable=False),
            sa.Column("text", sa.Text(), nullable=True),
            sa.Column("structured_json", sqlite.JSON(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(["thread_id"], ["ai_threads.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_ai_messages_thread_id"), "ai_messages", ["thread_id"], unique=False)

    if "ai_feedback" not in existing_tables:
        op.create_table(
            "ai_feedback",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column("user_id", sa.String(), nullable=False),
            sa.Column("thread_id", sa.String(), nullable=False),
            sa.Column("message_id", sa.String(), nullable=False),
            sa.Column("rating", sa.Integer(), nullable=False),
            sa.Column("tags", sqlite.JSON(), nullable=True),
            sa.Column("comment", sa.Text(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(["message_id"], ["ai_messages.id"]),
            sa.ForeignKeyConstraint(["thread_id"], ["ai_threads.id"]),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_ai_feedback_message_id"), "ai_feedback", ["message_id"], unique=False)
        op.create_index(op.f("ix_ai_feedback_thread_id"), "ai_feedback", ["thread_id"], unique=False)
        op.create_index(op.f("ix_ai_feedback_user_id"), "ai_feedback", ["user_id"], unique=False)

    if "ai_tool_calls" not in existing_tables:
        op.create_table(
            "ai_tool_calls",
            sa.Column("id", sa.String(), nullable=False),
            sa.Column("message_id", sa.String(), nullable=False),
            sa.Column("tool_name", sa.String(length=100), nullable=False),
            sa.Column("tool_args", sqlite.JSON(), nullable=False),
            sa.Column("tool_result", sqlite.JSON(), nullable=True),
            sa.Column("status", sa.String(length=20), nullable=False),
            sa.Column("latency_ms", sa.Integer(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(["message_id"], ["ai_messages.id"]),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(op.f("ix_ai_tool_calls_message_id"), "ai_tool_calls", ["message_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tool_calls_message_id'), table_name='ai_tool_calls')
    op.drop_table('ai_tool_calls')
    op.drop_index(op.f('ix_ai_feedback_user_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_thread_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_message_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_ai_messages_thread_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_ai_threads_user_id'), table_name='ai_threads')
    op.drop_index(op.f('ix_ai_threads_project_id'), table_name='ai_threads')
    op.drop_table('ai_threads')
    # ### end Alembic commands ###
