"""add estimation summary fields

Revision ID: f33fd9cc72aa
Revises: 
Create Date: 2025-12-29 13:01:42.503628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f33fd9cc72aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technicians_id'), table_name='technicians')
    op.drop_index(op.f('ix_technicians_name'), table_name='technicians')
    op.drop_table('technicians')
    op.add_column('estimations', sa.Column('estimate_id', sa.String(length=64), nullable=False))
    op.add_column('estimations', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('estimations', sa.Column('blob_path', sa.String(length=255), nullable=True))
    op.add_column('estimations', sa.Column('summary_json', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_estimations_estimate_id'), 'estimations', ['estimate_id'], unique=True)
    op.drop_column('estimations', 'breakdown')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimations', sa.Column('breakdown', sqlite.JSON(), nullable=True))
    op.drop_index(op.f('ix_estimations_estimate_id'), table_name='estimations')
    op.drop_column('estimations', 'summary_json')
    op.drop_column('estimations', 'blob_path')
    op.drop_column('estimations', 'location')
    op.drop_column('estimations', 'estimate_id')
    op.create_table('technicians',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('skill', sa.VARCHAR(length=120), nullable=False),
    sa.Column('location', sa.VARCHAR(length=120), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=False),
    sa.Column('verified', sa.BOOLEAN(), nullable=False),
    sa.Column('short_description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_technicians_name'), 'technicians', ['name'], unique=False)
    op.create_index(op.f('ix_technicians_id'), 'technicians', ['id'], unique=False)
    # ### end Alembic commands ###
